Update action.yml
Signed-off-by: quic-rnamburi <rnamburi@qti.qualcomm.com>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -154,7 +154,7 @@ runs:
         set -euo pipefail
         ACTION_DIR="${{ github.action_path }}"
         ARMOR_BINS_PATH="$(cat "${{ github.action_path }}/.armor_bins_path")"
-        PROJECT="${{ github.repository }}"
+        PROJECT_URL="${{ github.server_url }}/${{ github.repository }}"
         BRANCH="${{ inputs.branch-name }}"
         GITHUB_EVENT="${{ github.event_name }}"
         if [[ "$GITHUB_EVENT" == pull_request* ]]; then
@@ -170,7 +170,7 @@ runs:
           -e REPORT_FORMAT="${REPORT_FORMAT}" \
           -e LOG_LEVEL="${LOG_LEVEL}" \
           -e DUMP_AST_DIFF="${DUMP_AST_DIFF}" \
-          -e PROJECT="${PROJECT}" \
+          -e PROJECT_URL="${PROJECT_URL}" \
           -e BRANCH="${BRANCH}" \
           -e GITHUB_EVENT="${GITHUB_EVENT}" \
           -e PR_NUMBER="${PR_NUMBER}" \
@@ -213,6 +213,37 @@ runs:
         fi
         echo "Overall status: $STATUS"
         echo "res=$STATUS" >> "$GITHUB_OUTPUT"
+
+    - name: Upload folder to S3
+      shell: bash
+      run: |
+        set -e
+        FOLDER="${{ steps.run-armor.outputs.out-root }}"
+        BUCKET="s3://qli-stg-armor-gh-artifacts"
+        YYYY="$(date -u +'%Y')"
+        MM="$(date -u +'%m')"
+        DD="$(date -u +'%d')"
+        HH="$(date -u +'%H')"
+        HOST="$(printf '%s' "${{ github.server_url }}" | sed -E 's#^[a-zA-Z]+://##; s#/.*$##')"
+        PREFIX="${YYYY}/${MM}/${DD}/${HH}/${HOST}/${{ github.repository }}/${GITHUB_REF_NAME}/${{ github.run_id }}/files"
+        echo "Uploading artifacts to Destination: ${BUCKET}/${PREFIX}"
+        set +e
+        ERR_FILE="$(mktemp)"
+        aws s3 cp "${FOLDER}" "${BUCKET}/${PREFIX}" \
+          --recursive \
+          --content-type "application/octet-stream" \
+          --only-show-errors \
+          2> "${ERR_FILE}"
+        rc=$?
+        set -e
+        if [[ ${rc} -eq 0 ]]; then
+          echo "S3 upload succeeded."
+        else
+          reason="$(cat "${ERR_FILE}")"
+          echo "::error :: S3 upload FAILED (rc=${rc})."
+          echo "::error :: Reason: ${reason:-No error output captured}"
+        fi
+        rm -f "${ERR_FILE}"
 
     - name: Prepare ARMOR summary
       if: steps.intersection.outputs.has-intersection == 'true'
